package com.ludere.legacy;

/**
 * BuildConstants
 *
 * Auto-generated by the Autogen GitHub Actions workflow.
 * This stub is used for local builds only.
 * The workflow replaces this file with values parsed from config.xml.
 *
 * DO NOT edit this file manually if using the autogen pipeline.
 */
public final class BuildConstants {

    public static final String PACKAGE_NAME   = "com.ludere.legacy";
    public static final String VERSION        = "1.0";
    public static final String CORE_ID        = "";       // auto-detected at runtime
    public static final String ROM_FILE       = "";       // auto-detected at runtime
    public static final String APP_ID         = "";
    public static final String OVERLAY_PRESET = "default";
    public static final String SAVE_LOCATION  = "internal";

    private BuildConstants() {}
}
